### PR TITLE
We now use java 1.8

### PR DESCRIPTION
**Pull request by definite**

### CODE REVIEW

**Comment by seanf** [comment]
@definite I'm not sure if we can assume Java 1.8 for all client environments yet. eg Java 1.8 is available for RHEL 6, but it's not installed by default, and I don't think our scripts are currently smart enough to (a) guarantee the presence of Java 1.8 and (b) ensure they use it.

Also, there is no such signature as org.codehaus.mojo.signature:java18 yet. See https://github.com/mojohaus/animal-sniffer/issues/1 

In the server, I had to disable the animal-sniffer-maven-plugin. We might be able to use this third-party signature though: http://javalibs.com/artifact/org.kaazing.mojo.signature/java18

**Comment by definite** [comment]
For EL6 RPMs, it is easy to add Requires: java >=1.8.
As for animal-sniffer-maven-plugin, perhaps it is too early to change it at the moment.

**Comment by seanf** [comment]
> Requires: java >=1.8

That only ensures Java 1.8 is installed, not that it will be used by zanata
scripts.

And it will only work for the EPEL package, not for 0install, dist-zip,
homebrew...

On 13 November 2015 at 15:05, Ding-Yi Chen <notifications@github.com> wrote:

> For EL6 RPMs, it is easy to add Requires: java >=1.8.
> As for animal-sniffer-maven-plugin, perhaps it is too early to change it
> at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-parent/pull/47#issuecomment-156323056>.
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by definite** [comment]
Ok, how about source to 1.8 and target 1.7?

**Comment by seanf** [comment]
javac doesn't allow that, unfortunately. It can be done with retrolambda,
but it's a lot of mucking around for little gain (in the client's case).

On 17 November 2015 at 10:42, Ding-Yi Chen <notifications@github.com> wrote:

> Ok, how about source to 1.8 and target 1.7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-parent/pull/47#issuecomment-157221646>.
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
@definite Unfortunately I think we'll have to reject this for now, and stick to Java 1.7 on the client, unless we can ensure the client scripts use a Java 8 JVM.

**Pull request closed without merging**
