### PR TITLE
chore(dependency): use-latest-releases on minor versions

### PR DESCRIPTION
**Pull request by definite**
Minor version update on dependency.

### CODE REVIEW

**Comment by seanf** [comment]
@definite we shouldn't let these dependencies get ahead of Fedora 21, or we might start using APIs which aren't available to our Fedora package.  eg xom 1.0.

**Comment by djansen-redhat** [comment]
You misspelled dependency chore(dependnecy)

**Comment by seanf** [comment]
@definite it looks like Fedora now has xom 1.2: https://apps.fedoraproject.org/packages/xom

Perhaps we should look at updating these dependencies, but as I said before, we shouldn't get ahead of Fedora or there will be much pain.

**Comment by definite** [comment]
It might be better to investigate the dependency one-by-one, close this one.

**Pull request closed without merging**
